In [7]:
# GENERATES AN ARRAY OF GIVEN SHAPE WITH RANDOM VALUES BETWEEN 0-1

import numpy as np

a = np.random.random((2,3))

print(a)

[[0.9149353  0.81490068 0.79720257]
 [0.4072575  0.93133623 0.93637455]]


In [56]:
# GENERATES AN ARRAY OF GIVEN SHAPE WITH RANDOM VALUES BETWEEN 2-10 AS INTEGERS

a = np.random.randint(2,10, size=(2,3))

print(a)

[[6 4 9]
 [2 7 4]]


In [26]:
# CREATING A SEQUENCE OF NUMBERS IN ARRAY   A-RANGE IS ARRAY RANGE

s = np.arange(0 , 31 , 5)   # (beg (inc) , end(excl) , step)

print(type(s)) # IT STORES IN AN ARRAY AND NOT LIST

print(s)

print(s[2])

print(s[2:4])

print(s[::2])

<class 'numpy.ndarray'>
[ 0  5 10 15 20 25 30]
10
[10 15]
[ 0 10 20 30]


In [15]:
# TAKES A RANDOM NUMBER FROM THE GIVEN LIST

from numpy import random

x = random.choice([4,8,5,7,2])

print(x)

8


In [24]:
arr = np.arange(5)

print(arr)

arr2 = np.append(arr,10)

print(arr2)

arr2 = np.insert(arr, 2 , 50)

print(arr2)

arr2 = np.delete(arr2, 2)

print(arr2)

[0 1 2 3 4]
[ 0  1  2  3  4 10]
[ 0  1 50  2  3  4]
[0 1 2 3 4]


In [27]:
z = np.array([1,2,3,4,5])

x = z.copy()

x[0] = 32

print(z)

print(x)

[1 2 3 4 5]
[32  2  3  4  5]


In [34]:
# RESHAPING THE DIMESNIONS OF AN ARRAY

a = np.array([[1,2,3],[4,5,6]])

print(a.shape)

p = a.reshape(3,2) #no of elements should match with original

print(p.shape)

p = a.reshape(-1) #1d array

print(p.shape)

(2, 3)
(3, 2)
(6,)


In [39]:
for x in p:
    print(x)
    
for x in a:
    print(x)
    
for x in a:
    for y in x:
        print(y , end="")

1
2
3
4
5
6
[1 2 3]
[4 5 6]
123456

In [44]:
arr1 = np.array([1,2,4,5])

arr2 = np.array([1,5,65])

arr3 = np.concatenate((arr1 , arr2))

print(arr3)

[ 1  2  4  5  1  5 65]


In [46]:
arr4 = np.array_split(arr3,2)

print(arr4)

[array([1, 2, 4, 5]), array([ 1,  5, 65])]


In [49]:
k = np.where(arr1==5)

print(k)

(array([3], dtype=int64),)


In [50]:
z = np.array([7,97,3,1,98])

print(np.sort(z))

[ 1  3  7 97 98]


In [52]:
# FILTERED ARRAY

arr = np.array([41,24,24,54,21])

list = [True,True,False,True,False]

z = arr[list]

print(z)

[41 24 54]


In [53]:
# GENRETING A SEQUENCE OF NUMBER BETWEEN X AND Y , TOTAL NUMBERS IS Z linspace(x,y,z)

g = np.linspace(0,6,10)

print(g)  #LINEARLY SPACED NUMBERS

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [55]:
# CONVERTING 2D OR 3D ARRAY TO 1D ARRAY USING FLATTEN()

print(a)

fltarr = a.flatten()

print(fltarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [62]:
# CREATING AN MATRIX

mat = np.matrix([[1,2,3] , [5,64,6]])

print(mat)

print(type(mat))

# CREATING AN MATRIX FROM AN ARRAY

a = np.matrix(np.arange(1,13).reshape((3,4)))

print(a)

print(type(a))

[[ 1  2  3]
 [ 5 64  6]]
<class 'numpy.matrix'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.matrix'>


In [64]:
# ADDITION , REGULAR MULTIPLICATION AND MATRIX MULTIPLICATION OF ARRAYS

x = np.array([[1,2],
            [3,4]])
y = np.array([[5,6],
            [7,8]])

# ADDITION ELEMENT WISE

print("ADDITION : \n" , x+y)

# REGULAR MULTIPLICATION ELEMENT WISE

print("REGULAR MULT : \n" , x*y)

# MATRIX MULTIPLICATION

print("MATRIX MULT : \n" , x.dot(y))

ADDITION : 
 [[ 6  8]
 [10 12]]
REGULAR MULT : 
 [[ 5 12]
 [21 32]]
MATRIX MULT : 
 [[19 22]
 [43 50]]
